Update tests

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -426,7 +426,7 @@ jobs:
                   mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=11 -Druntime=glassfish -Ddocker=yes -DoutputDirectory=app/glassfish -Dgoals="clean package" | tee mvn_output.txt
 
                   MAVEN_EXIT_CODE=${PIPESTATUS[0]}
-                  WARN_MESSAGE="GlassFish only supports Docker for Java 17"
+                  WARN_MESSAGE="GlassFish only supports Docker for Java SE 17"
                   if ! { [ $MAVEN_EXIT_CODE -eq 0 ] && [ ! -f app/glassfish/jakartaee-hello-world/Dockerfile ] && grep -q "$WARN_MESSAGE" mvn_output.txt;  }; then
                       echo "Maven build failed, a Dockerfile was found, or the expected warning was not found. Test failed."
                       exit 1
@@ -1083,17 +1083,16 @@ jobs:
 
             - name: Run Archetype for EE 8, SE 21, Payara, with Docker
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=full -DjavaVersion=21 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package"
-                  docker build -t test-image app/payara/jakartaee-hello-world
-                  docker rmi test-image
-                  rm -rf app/payara
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=full -DjavaVersion=21 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package" | tee mvn_output.txt
 
-            - name: Run Archetype for EE 8 Web Profile, SE 21, Payara, with Docker
-              run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package"
-                  docker build -t test-image app/payara/jakartaee-hello-world
-                  docker rmi test-image
-                  rm -rf app/payara
+                  MAVEN_EXIT_CODE=${PIPESTATUS[0]}
+                  ERROR_MESSAGE="Payara 5 does not support Java SE 21"
+                  if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+                      echo "Maven build did not fail, or the expected error message was not found. Test failed."
+                      exit 1
+                  fi
+
+                  rm -f mvn_output.txt
 
             - name: Run Archetype for EE 10, SE 21, Payara, with Docker
               run: |
@@ -1137,32 +1136,52 @@ jobs:
                   docker rmi test-image
                   rm -rf app/payara
 
-            - name: Run Archetype for EE 8 Web Profile, SE 21, TomEE, with Docker
+            - name: Run Archetype for EE 8 Web Profile, SE 21, TomEE
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=tomee -Ddocker=yes -DoutputDirectory=app/tomee -Dgoals="clean package"
-                  docker build -t test-image app/tomee/jakartaee-hello-world
-                  docker rmi test-image
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=tomee -Ddocker=no -DoutputDirectory=app/tomee -Dgoals="clean package"
                   rm -rf app/tomee
 
-            - name: Run Archetype for EE 9.1 Web Profile, SE 21, TomEE, with Docker
+            - name: Run Archetype for EE 8 Web Profile, SE 21, TomEE, with Docker
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=21 -Druntime=tomee -Ddocker=yes -DoutputDirectory=app/tomee -Dgoals="clean package"
-                  docker build -t test-image app/tomee/jakartaee-hello-world
-                  docker rmi test-image
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=tomee -Ddocker=yes -DoutputDirectory=app/tomee -Dgoals="clean package" | tee mvn_output.txt
+
+                  MAVEN_EXIT_CODE=${PIPESTATUS[0]}
+                  WARN_MESSAGE="TomEE does not support Docker for Java SE 21"
+                  if ! { [ $MAVEN_EXIT_CODE -eq 0 ] && [ ! -f app/tomee/jakartaee-hello-world/Dockerfile ] && grep -q "$WARN_MESSAGE" mvn_output.txt;  }; then
+                      echo "Maven build failed, a Dockerfile was found, or the expected warning was not found. Test failed."
+                      exit 1
+                  fi
+
+                  rm -f mvn_output.txt
                   rm -rf app/tomee
+
+            - name: Run Archetype for EE 9.1 Web Profile, SE 21, TomEE
+              run: |
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=21 -Druntime=tomee -Ddocker=no -DoutputDirectory=app/tomee -Dgoals="clean package"
+                  rm -rf app/tomee
+
+            - name: Run Archetype for EE 8, SE 21, WildFly
+              run: |
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=full -DjavaVersion=21 -Druntime=wildfly -Ddocker=no -DoutputDirectory=app/wildfly -Dgoals="clean package"
+                  rm -rf app/wildfly
 
             - name: Run Archetype for EE 8, SE 21, WildFly, with Docker
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=full -DjavaVersion=21 -Druntime=wildfly -Ddocker=yes -DoutputDirectory=app/wildfly -Dgoals="clean package"
-                  docker build -t test-image app/wildfly/jakartaee-hello-world
-                  docker rmi test-image
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=full -DjavaVersion=21 -Druntime=wildfly -Ddocker=yes -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
+
+                  MAVEN_EXIT_CODE=${PIPESTATUS[0]}
+                  WARN_MESSAGE="WildFly 26 does not support Docker for Java SE 21"
+                  if ! { [ $MAVEN_EXIT_CODE -eq 0 ] && [ ! -f app/wildfly/jakartaee-hello-world/Dockerfile ] && grep -q "$WARN_MESSAGE" mvn_output.txt;  }; then
+                      echo "Maven build failed, a Dockerfile was found, or the expected warning was not found. Test failed."
+                      exit 1
+                  fi
+
+                  rm -f mvn_output.txt
                   rm -rf app/wildfly
 
-            - name: Run Archetype for EE 8 Web Profile, SE 21, WildFly, with Docker
+            - name: Run Archetype for EE 8 Web Profile, SE 21, WildFly
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=wildfly -Ddocker=yes -DoutputDirectory=app/wildfly -Dgoals="clean package"
-                  docker build -t test-image app/wildfly/jakartaee-hello-world
-                  docker rmi test-image
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=21 -Druntime=wildfly -Ddocker=no -DoutputDirectory=app/wildfly -Dgoals="clean package"
                   rm -rf app/wildfly
 
             - name: Run Archetype for EE 10, SE 21, WildFly, with Docker
