Add explicit failure check for negative cases

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -38,12 +38,18 @@ jobs:
 
 
       - name: Run Archetype for EE 8 Core Profile, SE 8
+        id: ee_8_core_se_8_none
         continue-on-error: true
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_8_core_se_8_none'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 8 Core Profile, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
+
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
@@ -62,12 +68,18 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9 Core Profile, SE 8
+        id: ee_9_core_se_8_none
         continue-on-error: true
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_9_core_se_8_none'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 9 Core Profile, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
+          
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
@@ -86,12 +98,18 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9.1 Core Profile, SE 8
+        id: ee_9_1_core_se_8_none
         continue-on-error: true
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_9_1_core_se_8_none'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 9.1 Core Profile, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
+
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
@@ -100,12 +118,18 @@ jobs:
           rm mvn_output.txt
 
       - name: Run Archetype for EE 10, SE 8
+        id: ee_10_full_se_8_none
         continue-on-error: true
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_10_full_se_8_none'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 10, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
+
           ERROR_MESSAGE="Jakarta EE 10 does not support Java SE 8"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
@@ -257,11 +281,17 @@ jobs:
 
       - name: Run Archetype for EE 9, SE 8, WildFly
         continue-on-error: true
+        id: ee_9_full_se_8_wildfly
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_9_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 9, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
+
           ERROR_MESSAGE="WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
@@ -270,12 +300,17 @@ jobs:
           rm mvn_output.txt
 
       - name: Run Archetype for EE 9.1, SE 8, WildFly
+        id: ee_9_1_full_se_8_wildfly
         continue-on-error: true
         run: |
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
+          if [[ "${{ steps['ee_9_1_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
+            echo "Maven build for EE 9.1, SE 8, without Docker succeeded, test failed."
+            exit 1
+          fi
           ERROR_MESSAGE="WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
           if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
             echo "Expected error message not found in the Maven output."
