Disable Payara 7 and SE 17

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -838,24 +838,14 @@ jobs:
 
             - name: Run Archetype for EE 11, SE 17, Payara, with Docker
               run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=11 -Dprofile=full -DjavaVersion=17 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package"
-                  docker build -t test-image app/payara/jakartaee-hello-world
-                  docker rmi test-image
-                  rm -rf app/payara
-
-            - name: Run Archetype for EE 11 Web Profile, SE 17, Payara, with Docker
-              run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=11 -Dprofile=web -DjavaVersion=17 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package"
-                  docker build -t test-image app/payara/jakartaee-hello-world
-                  docker rmi test-image
-                  rm -rf app/payara
-
-            - name: Run Archetype for EE 11 Core Profile, SE 17, Payara, with Docker
-              run: |
-                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=11 -Dprofile=core -DjavaVersion=17 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package"
-                  docker build -t test-image app/payara/jakartaee-hello-world
-                  docker rmi test-image
-                  rm -rf app/payara
+                mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=11 -Dprofile=full -DjavaVersion=17 -Druntime=payara -Ddocker=yes -DoutputDirectory=app/payara -Dgoals="clean package" | tee mvn_output.txt
+                MAVEN_EXIT_CODE=${PIPESTATUS[0]}
+                ERROR_MESSAGE="Payara 7 with Jakarta EE 11 only supports Java SE 21 and above"
+                if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+                  echo "Maven build did not fail, or the expected error message was not found. Test failed."
+                  exit 1
+                fi
+                rm -f mvn_output.txt
 
             - name: Run Archetype for EE 8 Web Profile, SE 17, TomEE, with Docker
               run: |
