Remove redundant else clause

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -38,21 +38,16 @@ jobs:
 
 
       - name: Run Archetype for EE 8 Core Profile, SE 8
-        id: ee_8_core_se_8_none
-        continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" > mvn_output.txt 2>&1
-
-      - name: Check Maven Build Status and Error Message
-        run: |
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
+          
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
-          if [[ "${{ steps['ee_8_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 8 Core Profile, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Run Archetype for EE 9, SE 8
@@ -66,21 +61,16 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9 Core Profile, SE 8
-        id: ee_9_core_se_8_none
-        continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" > mvn_output.txt 2>&1
-
-      - name: Check Maven Build Status and Error Message
-        run: |
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
+  
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
-          if [[ "${{ steps['ee_9_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9 Core Profile, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Run Archetype for EE 9.1, SE 8
@@ -94,39 +84,29 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9.1 Core Profile, SE 8
-        id: ee_9_1_core_se_8_none
-        continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" > mvn_output.txt 2>&1
-
-      - name: Check Maven Build Status and Error Message
-        run: |
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
+  
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="Core Profile is only supported for Jakarta EE 10"
-          if [[ "${{ steps['ee_9_1_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9.1 Core Profile, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Run Archetype for EE 10, SE 8
-        id: ee_10_full_se_8_none
-        continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" > mvn_output.txt 2>&1
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
-      - name: Check Maven Build Status and Error Message
-        run: |
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="Jakarta EE 10 does not support Java SE 8"
-          if [[ "${{ steps['ee_10_full_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 10, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Run Archetype for EE 8, SE 8, GlassFish
@@ -272,39 +252,29 @@ jobs:
           rm -rf app/wildfly
 
       - name: Run Archetype for EE 9, SE 8, WildFly
-        continue-on-error: true
-        id: ee_9_full_se_8_wildfly
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" > mvn_output.txt 2>&1
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
-      - name: Check Maven Build Status and Error Message
-        run: |
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
-          if [[ "${{ steps['ee_9_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Run Archetype for EE 9.1, SE 8, WildFly
-        id: ee_9_1_full_se_8_wildfly
-        continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" > mvn_output.txt 2>&1
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
-      - name: Check Maven Build Status and Error Message
-        run: |
+          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
           ERROR_MESSAGE="WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
-          if [[ "${{ steps['ee_9_1_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9.1, SE 8, without Docker succeeded, test failed."
-            exit 1
-          elif ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
-            echo "Expected error message not found in the Maven output."
-            exit 1
+          if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+              echo "Maven build did not fail, or the expected error message was not found. Test Failed."
+              exit 1
           fi
+          
           rm -f mvn_output.txt
 
       - name: Set up Java SE 11
