Add negative EE 11 test.

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -906,6 +906,19 @@ jobs:
                   docker rmi test-image
                   rm -rf app/wildfly
 
+            - name: Run Archetype for EE 11, SE 17, WildFly
+              run: |
+                  mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.8.0-SNAPSHOT -DjakartaVersion=11 -Dprofile=full -DjavaVersion=17 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
+
+                  MAVEN_EXIT_CODE=${PIPESTATUS[0]}
+                  ERROR_MESSAGE="only Payara currently supports Jakarta EE 11 in a stable release"
+                  if ! { [ $MAVEN_EXIT_CODE -ne 0 ] && grep -q "$ERROR_MESSAGE" mvn_output.txt; }; then
+                      echo "Maven build did not fail, or the expected error message was not found. Test failed."
+                      exit 1
+                  fi
+
+                  rm -f mvn_output.txt                  
+
             - name: Set up Java SE 21
               uses: actions/setup-java@v4
               with:
