Refactored the negative cases to check for error messages

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -36,18 +36,20 @@ jobs:
           mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package"
           rm -rf app
 
+
       - name: Run Archetype for EE 8 Core Profile, SE 8
-        id: ee_8_core_se_8_none
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_8_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 8 Core Profile, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, the Core Profile is only supported for Jakarta EE 10"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Run Archetype for EE 9, SE 8
         run: |
@@ -60,17 +62,18 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9 Core Profile, SE 8
-        id: ee_9_core_se_8_none
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_9_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9 Core Profile, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, the Core Profile is only supported for Jakarta EE 10"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Run Archetype for EE 9.1, SE 8
         run: |
@@ -83,30 +86,32 @@ jobs:
           rm -rf app
 
       - name: Run Archetype for EE 9.1 Core Profile, SE 8
-        id: ee_9_1_core_se_8_none
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=core -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_9_1_core_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9.1 Core Profile, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, the Core Profile is only supported for Jakarta EE 10"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Run Archetype for EE 10, SE 8
-        id: ee_10_full_se_8_none
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=10 -Dprofile=full -DjavaVersion=8 -DoutputDirectory=app -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_10_full_se_8_none'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 10, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, Jakarta EE 10 does not support Java SE 8"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Run Archetype for EE 8, SE 8, GlassFish
         run: |
@@ -246,30 +251,32 @@ jobs:
           rm -rf app/wildfly
 
       - name: Run Archetype for EE 9, SE 8, WildFly
-        id: ee_9_full_se_8_wildfly
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_9_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Run Archetype for EE 9.1, SE 8, WildFly
-        id: ee_9_1_full_se_8_wildfly
         continue-on-error: true
         run: |
-          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package"
+          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=full -DjavaVersion=8 -Druntime=wildfly -DoutputDirectory=app/wildfly -Dgoals="clean package" | tee mvn_output.txt
 
       - name: Check Maven Build Status
         run: |
-          if [[ "${{ steps['ee_9_1_full_se_8_wildfly'].outcome }}" != "failure" ]]; then
-            echo "Maven build for EE 9.1, SE 8, without Docker succeeded, test failed."
+          ERROR_MESSAGE="Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jakarta-starter-modules: Failed, WildFly does not offer a release for Jakarta EE 9 or Jakarta EE 9.1"
+          if ! grep -q "$ERROR_MESSAGE" mvn_output.txt; then
+            echo "Expected error message not found in the Maven output."
             exit 1
           fi
+          rm mvn_output.txt
 
       - name: Set up Java SE 11
         uses: actions/setup-java@v4
